### ISSUE TITLE
Problem setting Theme 

### ISSUE THREAD

**Issue by spences10** [taniarascia/new-moon-vscode#1]
I get an error trying to use the theme:

![image](https://cloud.githubusercontent.com/assets/234708/26413064/b0620ea4-40a2-11e7-8c15-279b2d12b412.png)

I'm on Windows 7 behind a corporate proxy I will try on my own machine [Win 10] later today.

**Comment by taniarascia** [comment]
Hmm. I just tried installing from scratch on a Mac and it works fine. I'll see what the issue is.

**Comment by taniarascia** [comment]
Do you still have this issue?

**Comment by spences10** [comment]
Hey, I haven't checked, let me look now

**Comment by spences10** [comment]
Seems fine on my home machine, must be because I was behind a proxy?

![image](https://cloud.githubusercontent.com/assets/234708/26654588/4dd4fd3e-464f-11e7-84a9-2ee4f71400f1.png)

**Comment by taniarascia** [comment]
Cool, glad it works.
