### ISSUE TITLE
Failed to update 'taniarascia.new-moon-vscode'.

### ISSUE THREAD

**Issue by max8hine** [taniarascia/new-moon-vscode#3]
it's been 2 weeks now.
Failed to update **New Moon**, even after restart my computer

VScode, latest
OS: macOS High Sierra

![image](https://user-images.githubusercontent.com/15165714/39102727-7d5d9848-46fa-11e8-934d-8fe90e237b96.png)

![image](https://user-images.githubusercontent.com/15165714/39102766-d050c11a-46fa-11e8-914a-706985c344bb.png)

**Comment by taniarascia** [comment]
I'm using macOS High Sierra and the latest version of Visual Studio Code. I completely deleted and reinstalled New Moon with no problems. I currently have it installed on two Macs running High Sierra and the latest version of Visual Studio code. Have you tried uninstalling it and reinstalling it? I can't replicate this issue.

**Comment by max8hine** [comment]
No success, after uninstall **New Moon**
even reload vscode or reopen vscode, still have an error during installation.
![image](https://user-images.githubusercontent.com/15165714/39103285-036bc8b2-46fe-11e8-9ef4-b23c804e4781.png)

Tried to delete the old file in `$HOME/.vscode/extensions`, but the result still the same.

I tried to install manually by doing something like
`code myExtensionFolder\newmoon.vsix`
 but got this result
![image](https://user-images.githubusercontent.com/15165714/39103250-cb18d6ee-46fd-11e8-9b3c-238d779812f2.png)

There is no error I could report, and yes, it's difficult to replicate the issue.

It is possible due to my personal environment.

**Comment by taniarascia** [comment]
I have not had any other reports of failed installations. I can only assume there is another extension 
 you have installed that is conflicting with it. The entire New Moon extension only consists of a JSON file with colors in it, so I'm not really sure what could be the issue.

**Comment by max8hine** [comment]
I've been thinking the same of conflicting with other extensions. It's more likely not the **new moon** issue. 
Thank you for the prompt response. I will try it later =)
