### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by shubhamtiwari23** [taniarascia/new-moon-vscode#5]
very nice theme 
can you add a italic version of this theme

**Comment by taniarascia** [comment]
Hi! All you have to do is add this to the `new-moon.json` file.

```
"settings": {
  "fontStyle": "italic"
},
```

**Comment by swrobel** [comment]
@taniarascia not sure if I'm doing this right, but it doesn't seem to be working for me. I edited `~/.vscode/extensions/taniarascia.new-moon-vscode-1.8.8/themes/new-moon.json` like so (the rest of the file isn't included for brevity) but it doesn't seem to have enabled italics for keywords, as I assumed it would (in fact nothing in my syntax seems to be in italics).

```json
{
  "name": "New Moon",
  "type": "dark",
  "settings": {
	 "fontStyle": "italic"
  },
  "colors": {
```
