### ISSUE TITLE
New moon iterm2 theme

### ISSUE THREAD

**Issue by WindSoilder** [taniarascia/new-moon-vscode#6]
Sorry, this is not actual issue here.

I love the theme very much.
I'm using iterm2 every day:)  Thanks for your color palette, I have created [new-moon  iterm2](https://github.com/WindSoilder/NewMoon-iterm2) theme easily.  

Anyway, very thanks for your theme:)

**Comment by taniarascia** [comment]
Awesome! I didn't see that you made that, so I made one myself [here](https://github.com/taniarascia/new-moon/tree/master/iterm2). I'll try yours out and see if I like it more. I'm glad you love the theme!
