### ISSUE TITLE
Variables look like errors imo

### ISSUE THREAD

**Issue by cadamsdev** [taniarascia/new-moon-vscode#9]
Do you think it would be better to use a different color other than red for variables?
`#f2777a`

This javascript file looks like it's loaded with errors imo
![image](https://user-images.githubusercontent.com/12568665/77220026-aa0bd000-6b09-11ea-9a4b-241164c765a4.png)

**Comment by taniarascia** [comment]
Yeah...they're read to differentiate between JSX/HTML in files...there's a New Moon Blue that has the variables red and blue reversed if you want to try that out.

**Comment by taniarascia** [comment]
<img width="826" alt="Screen Shot 2020-03-21 at 5 03 45 PM" src="https://user-images.githubusercontent.com/11951801/77237405-f1d83900-6b95-11ea-8a56-fbb53171627d.png">

**Comment by cadamsdev** [comment]
@taniarascia I'll try it out, thanks
